import { inject, type Module } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { RoboMLanguageGeneratedModule, RoboMLanguageGeneratedSharedModule } from './generated/module.js';
import { RoboMLanguageValidator, registerValidationChecks } from './robo-m-language-validator.js';
import { RoboMLanguageAcceptWeaver } from '../semantics/robo-m-language-accept-weaver.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RoboMLanguageAddedServices = {
    validation: {
        RoboMLanguageValidator: RoboMLanguageValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RoboMLanguageServices = LangiumServices & RoboMLanguageAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RoboMLanguageModule: Module<RoboMLanguageServices, PartialLangiumServices & RoboMLanguageAddedServices> = {
    validation: {
        RoboMLanguageValidator: () => new RoboMLanguageValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRoboMLanguageServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    RoboMLanguage: RoboMLanguageServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RoboMLanguageGeneratedSharedModule
    );
    const RoboMLanguage = inject(
        createDefaultModule({ shared }),
        RoboMLanguageGeneratedModule,
        RoboMLanguageModule
    );
    shared.ServiceRegistry.register(RoboMLanguage);
    registerValidationChecks(RoboMLanguage);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
Timestamps: 41
    new RoboMLanguageAcceptWeaver(RoboMLanguage);

    return { shared, RoboMLanguage };
}
